"""Original OPI-style personality practice question bank.
Not an official ISSB question bank.
"""

TRAITS = {
    "self_confidence": "Self-confidence",
    "leadership": "Leadership",
    "teamwork": "Teamwork",
    "emotional_stability": "Emotional stability",
    "integrity": "Integrity",
    "responsibility": "Responsibility",
    "adaptability": "Adaptability",
    "communication": "Communication",
    "initiative": "Initiative",
    "discipline": "Discipline",
}

OPTIONS = ["Strongly Agree", "Agree", "Slightly Agree", "Slightly Disagree", "Disagree", "Strongly Disagree"]

# 100 stems x 2 forms = 200 questions. Forms are intentionally worded differently
# so that the same underlying trait is checked from more than one angle.
BASE = [
("self_confidence", "I can speak confidently when several people are listening.", False),
("self_confidence", "I trust myself to make a sensible decision when guidance is limited.", False),
("self_confidence", "I hesitate to express an idea because I fear being judged.", True),
("self_confidence", "I remain composed when someone challenges my opinion.", False),
("self_confidence", "I often assume that others are more capable than I am.", True),
("self_confidence", "I can accept criticism without losing confidence in myself.", False),
("self_confidence", "I avoid unfamiliar responsibilities because I doubt my ability.", True),
("self_confidence", "I am comfortable asking questions when I do not understand something.", False),
("self_confidence", "I can recover my confidence after making a mistake.", False),
("self_confidence", "I usually need repeated reassurance before acting.", True),
("leadership", "In a group, I am willing to take responsibility for the final outcome.", False),
("leadership", "When a team is confused, I help organize the next steps.", False),
("leadership", "I prefer others to make difficult decisions even when I am capable of helping.", True),
("leadership", "I can give clear direction without humiliating people.", False),
("leadership", "I naturally look for ways to help a group move toward its objective.", False),
("leadership", "I avoid taking charge because leadership creates too much pressure.", True),
("leadership", "I can accept responsibility when a team decision goes wrong.", False),
("leadership", "I listen to different views before choosing a course of action.", False),
("leadership", "I expect people to follow me even when I have not earned their trust.", True),
("leadership", "I can motivate others during a difficult task.", False),
("teamwork", "I willingly help a teammate who is struggling with a task.", False),
("teamwork", "I can put the team's objective ahead of my personal preference.", False),
("teamwork", "I become irritated when others do not work exactly as I do.", True),
("teamwork", "I share useful information with teammates instead of keeping it to myself.", False),
("teamwork", "I can disagree with a teammate without turning the disagreement personal.", False),
("teamwork", "I prefer working alone even when cooperation would produce a better result.", True),
("teamwork", "I give credit to teammates for their contributions.", False),
("teamwork", "I can adjust my approach to fit a group task.", False),
("teamwork", "I feel threatened when another team member performs better than me.", True),
("teamwork", "I can support a group decision after my own suggestion is not selected.", False),
("emotional_stability", "I stay reasonably calm when plans suddenly change.", False),
("emotional_stability", "I can think clearly when I am under pressure.", False),
("emotional_stability", "Small problems can ruin my mood for the entire day.", True),
("emotional_stability", "I recover fairly quickly after disappointment.", False),
("emotional_stability", "I can control an angry reaction long enough to respond sensibly.", False),
("emotional_stability", "I find it difficult to concentrate when I feel stressed.", True),
("emotional_stability", "I remain patient when another person makes a mistake.", False),
("emotional_stability", "I can handle uncertainty without repeatedly imagining the worst outcome.", False),
("emotional_stability", "I become overwhelmed easily when several things go wrong together.", True),
("emotional_stability", "I try to separate facts from emotions before reacting to a problem.", False),
("integrity", "I tell the truth even when honesty may put me at a disadvantage.", False),
("integrity", "I return money or property that does not belong to me.", False),
("integrity", "A small lie is acceptable whenever it helps me avoid blame.", True),
("integrity", "I admit my mistakes instead of hiding them.", False),
("integrity", "I avoid taking credit for work done mainly by someone else.", False),
("integrity", "Rules matter only when there is a realistic chance of being caught.", True),
("integrity", "I would report a serious mistake that could harm others.", False),
("integrity", "I try to keep promises that I make.", False),
("integrity", "Getting an unfair advantage is acceptable if nobody notices.", True),
("integrity", "I would rather accept a loss than deliberately deceive someone.", False),
("responsibility", "I complete important tasks even when nobody is checking on me.", False),
("responsibility", "I plan ahead when I know a deadline is approaching.", False),
("responsibility", "I often blame circumstances when I fail to finish my duties.", True),
("responsibility", "I take ownership of mistakes that are partly my fault.", False),
("responsibility", "People can generally rely on me to do what I said I would do.", False),
("responsibility", "I postpone difficult duties until someone reminds me repeatedly.", True),
("responsibility", "I check my work before considering it complete.", False),
("responsibility", "I think about the consequences of my actions before acting.", False),
("responsibility", "I sometimes leave responsibilities unfinished because I lose interest.", True),
("responsibility", "I can manage my time when several obligations compete for attention.", False),
("adaptability", "I can adjust quickly when a familiar plan no longer works.", False),
("adaptability", "I am willing to learn a new method even when the old one feels easier.", False),
("adaptability", "Unexpected changes usually make me resist the task completely.", True),
("adaptability", "I can work effectively with people whose style differs from mine.", False),
("adaptability", "I can change my opinion when strong evidence proves me wrong.", False),
("adaptability", "I dislike changing routines even when the change clearly improves the result.", True),
("adaptability", "I can remain productive in an unfamiliar environment.", False),
("adaptability", "I look for another solution when the first approach fails.", False),
("adaptability", "I need everything to happen exactly as expected before I can perform well.", True),
("adaptability", "I can learn from a setback and modify my approach.", False),
("communication", "I explain my point in a way that others can understand.", False),
("communication", "I listen carefully before responding to another person's view.", False),
("communication", "I interrupt people because I usually know what they are going to say.", True),
("communication", "I can discuss a disagreement without becoming insulting.", False),
("communication", "I ask for clarification rather than pretending I understood.", False),
("communication", "I avoid speaking about problems because difficult conversations make me uncomfortable.", True),
("communication", "I can communicate the main point without adding unnecessary details.", False),
("communication", "I pay attention to how my words may affect other people.", False),
("communication", "I sometimes use vague language so I cannot be held responsible for what I said.", True),
("communication", "I can give and receive feedback respectfully.", False),
("initiative", "When I notice a useful improvement, I take reasonable steps to act on it.", False),
("initiative", "I start important work without waiting for someone to push me.", False),
("initiative", "I usually wait for explicit instructions even when the next step is obvious.", True),
("initiative", "I look for practical ways to solve a problem before complaining about it.", False),
("initiative", "I volunteer for tasks when I believe I can contribute.", False),
("initiative", "I avoid opportunities because failure would be embarrassing.", True),
("initiative", "I can make a reasonable decision with incomplete information.", False),
("initiative", "I prepare for likely problems before they become urgent.", False),
("initiative", "I prefer to do nothing until someone else takes the first step.", True),
("initiative", "I take action when a situation clearly requires attention.", False),
("discipline", "I can follow a routine even when I do not feel motivated.", False),
("discipline", "I usually arrive on time for important commitments.", False),
("discipline", "I often sacrifice important duties for short-term entertainment.", True),
("discipline", "I can keep working on a boring task until it is finished.", False),
("discipline", "I maintain reasonable standards even when nobody is observing me.", False),
("discipline", "I frequently break personal rules that I set for myself.", True),
("discipline", "I organize my priorities before spending time on less important activities.", False),
("discipline", "I can resist distractions when a task needs concentration.", False),
("discipline", "I tend to depend on last-minute pressure to get things done.", True),
("discipline", "I follow agreed procedures when they are important for safety or quality.", False),
]

QUESTIONS = []
qid = 1
pair_id = 1

# Create paired/rephrased items for 100 base statements.
for trait, stem, reverse in BASE:
    # Primary form
    QUESTIONS.append({
        "id": f"Q{qid:03d}",
        "trait": trait,
        "text": stem,
        "reverse": reverse,
        "pair_id": None,
    })
    qid += 1

# Build 100 second-form questions with controlled semantic opposites/rephrasings.
PAIR_BASE = [
    ("self_confidence", "I am comfortable presenting my view even when others disagree with me.", False),
    ("self_confidence", "I can trust my judgment in ordinary unfamiliar situations.", False),
    ("self_confidence", "Fear of making a bad impression often stops me from contributing.", True),
    ("self_confidence", "A respectful challenge does not make me doubt my worth.", False),
    ("self_confidence", "I usually believe I will perform worse than people around me.", True),
    ("self_confidence", "Negative feedback can help me improve without destroying my confidence.", False),
    ("self_confidence", "I back away from tasks when I am not sure I will succeed.", True),
    ("self_confidence", "I can admit that I do not know something without feeling weak.", False),
    ("self_confidence", "After a setback, I can regain focus and try again.", False),
    ("self_confidence", "I frequently look to others to tell me whether my decision is acceptable.", True),
    ("leadership", "I am willing to coordinate people when a group needs direction.", False),
    ("leadership", "I help turn a vague group problem into clear actions.", False),
    ("leadership", "I avoid difficult decisions even when the group expects guidance from me.", True),
    ("leadership", "I can correct a teammate firmly without being disrespectful.", False),
    ("leadership", "I often notice what a team needs in order to keep progressing.", False),
    ("leadership", "I prefer to stay in the background even when I am the best person to organize the task.", True),
    ("leadership", "I do not shift blame to teammates when a decision I led fails.", False),
    ("leadership", "Before directing others, I try to understand their perspectives.", False),
    ("leadership", "I think people should obey me simply because I am confident.", True),
    ("leadership", "I encourage teammates when a demanding task starts to wear them down.", False),
    ("teamwork", "I step in when a teammate needs practical assistance.", False),
    ("teamwork", "I can compromise when it helps the group achieve its goal.", False),
    ("teamwork", "I get frustrated when teammates use a different but effective method.", True),
    ("teamwork", "I share information that can help the whole group succeed.", False),
    ("teamwork", "I can challenge an idea without attacking the person who suggested it.", False),
    ("teamwork", "I would rather struggle alone than ask the team for help.", True),
    ("teamwork", "I recognize the efforts of others when a team succeeds.", False),
    ("teamwork", "I can adapt my role when the needs of the team change.", False),
    ("teamwork", "Another person's success does not reduce my value.", False),
    ("teamwork", "I can accept a group choice even when my proposal loses.", False),
    ("emotional_stability", "Unexpected changes do not easily throw me off balance.", False),
    ("emotional_stability", "Pressure usually does not prevent me from thinking logically.", False),
    ("emotional_stability", "I can stay upset for a long time over minor setbacks.", True),
    ("emotional_stability", "After something goes badly, I can return to normal functioning fairly soon.", False),
    ("emotional_stability", "I can pause before responding when I am angry.", False),
    ("emotional_stability", "Stress can make my thinking so unclear that I stop functioning well.", True),
    ("emotional_stability", "I try to remain patient when people make avoidable mistakes.", False),
    ("emotional_stability", "Not knowing the outcome does not automatically make me panic.", False),
    ("emotional_stability", "When several problems happen at once, I quickly feel unable to cope.", True),
    ("emotional_stability", "I try to respond to facts rather than the first emotion I feel.", False),
    ("integrity", "I value truthfulness even when it costs me something.", False),
    ("integrity", "I return things that I know belong to another person.", False),
    ("integrity", "Avoiding consequences is a good enough reason to mislead someone.", True),
    ("integrity", "I acknowledge mistakes that I have made.", False),
    ("integrity", "I give proper credit for another person's work.", False),
    ("integrity", "If nobody can discover it, breaking a rule is sometimes acceptable.", True),
    ("integrity", "I speak up about serious errors that could affect others.", False),
    ("integrity", "I make an effort to honor commitments I give to people.", False),
    ("integrity", "Winning unfairly is still wrong even when I can get away with it.", False),
    ("integrity", "I prefer a fair loss over deliberately misleading another person.", False),
    ("responsibility", "I can be trusted to handle duties without constant supervision.", False),
    ("responsibility", "I make a practical schedule when an important deadline is coming.", False),
    ("responsibility", "I commonly explain away failures instead of considering my own part in them.", True),
    ("responsibility", "When I contribute to a mistake, I acknowledge my responsibility.", False),
    ("responsibility", "Others can normally depend on me for commitments I accept.", False),
    ("responsibility", "I frequently need other people to remind me about obligations.", True),
    ("responsibility", "I review important work for errors before submitting it.", False),
    ("responsibility", "I consider likely consequences before making important choices.", False),
    ("responsibility", "I sometimes abandon duties once the initial excitement is gone.", True),
    ("responsibility", "I can allocate my time when several responsibilities arrive together.", False),
    ("adaptability", "I can change course when new circumstances make the original plan unsuitable.", False),
    ("adaptability", "I am open to learning better methods instead of defending old habits.", False),
    ("adaptability", "An unexpected change can make me refuse to continue the task.", True),
    ("adaptability", "I can cooperate with people who approach work differently from me.", False),
    ("adaptability", "Evidence can convince me to revise a position I previously held strongly.", False),
    ("adaptability", "I prefer familiar routines even when they clearly reduce efficiency.", True),
    ("adaptability", "I can function reasonably well when the surroundings are unfamiliar.", False),
    ("adaptability", "When an approach fails, I look for a workable alternative.", False),
    ("adaptability", "I struggle to perform when the situation does not match my expectations.", True),
    ("adaptability", "A setback can teach me to change how I approach the next attempt.", False),
    ("communication", "I try to make my explanation understandable to the other person.", False),
    ("communication", "I listen to understand rather than only waiting for my turn to talk.", False),
    ("communication", "I often speak over people because I assume their point is obvious.", True),
    ("communication", "I can disagree firmly without becoming disrespectful.", False),
    ("communication", "When a message is unclear, I ask questions before acting on it.", False),
    ("communication", "I avoid necessary conversations because they may feel uncomfortable.", True),
    ("communication", "I can state the essential message without making it confusing.", False),
    ("communication", "I consider how a message may be interpreted by others.", False),
    ("communication", "I sometimes keep my wording deliberately unclear so I can deny responsibility later.", True),
    ("communication", "I can discuss feedback without treating it as a personal attack.", False),
    ("initiative", "When I see a practical improvement, I am willing to start working on it.", False),
    ("initiative", "I can begin useful work without someone repeatedly reminding me.", False),
    ("initiative", "Even obvious next steps often wait until a senior person tells me to act.", True),
    ("initiative", "I try a reasonable solution before deciding that a problem is impossible.", False),
    ("initiative", "I volunteer when I have a useful skill for a task.", False),
    ("initiative", "I sometimes avoid chances to grow because failure might embarrass me.", True),
    ("initiative", "I can make a reasonable first move even when every detail is not known.", False),
    ("initiative", "I prepare for foreseeable obstacles before they become urgent.", False),
    ("initiative", "I normally wait for someone else to begin before I contribute.", True),
    ("initiative", "I act when a problem clearly needs attention rather than only discussing it.", False),
    ("discipline", "I can stick to necessary routines even on days when motivation is low.", False),
    ("discipline", "I take punctuality seriously for important commitments.", False),
    ("discipline", "Short-term entertainment sometimes matters more to me than completing important duties.", True),
    ("discipline", "I can maintain effort on repetitive work until it is finished.", False),
    ("discipline", "I keep reasonable standards even when nobody is supervising me.", False),
    ("discipline", "I regularly ignore limits that I have personally set for myself.", True),
    ("discipline", "I decide priorities before giving attention to low-value activities.", False),
    ("discipline", "I can put distractions aside when concentration matters.", False),
    ("discipline", "I rely heavily on deadline pressure because I delay until the last moment.", True),
    ("discipline", "I follow important procedures even when skipping them would be quicker.", False),
]

for idx, (trait, stem, reverse) in enumerate(PAIR_BASE, start=1):
    QUESTIONS.append({
        "id": f"Q{qid:03d}",
        "trait": trait,
        "text": stem,
        "reverse": reverse,
        "pair_id": f"P{idx:03d}",
    })
    # Pair each second-form item with the same-trait item from the first block.
    # BASE was deliberately ordered in groups of 10 per trait.
    first_id = f"Q{(idx):03d}"
    QUESTIONS[-1]["paired_question_id"] = first_id
    # annotate the original item too
    for q in QUESTIONS:
        if q["id"] == first_id:
            q["pair_id"] = f"P{idx:03d}"
            q["paired_question_id"] = f"Q{qid:03d}"
            break
    qid += 1



# Additional 100 paired items (10 per trait). These expand the pool to 400 questions
# so later attempts can contain genuinely different MCQs, not only a different order.
EXTRA_BASE = [
("self_confidence", "I can state my position clearly without needing everyone to agree with me.", False),
("self_confidence", "I am willing to try a demanding task when I have a reasonable chance of success.", False),
("self_confidence", "I compare myself with others so much that it weakens my confidence.", True),
("self_confidence", "I can remain confident while still admitting my limitations.", False),
("self_confidence", "I become quiet when people around me seem more experienced.", True),
("self_confidence", "I can make a decision and explain the reasons for it.", False),
("self_confidence", "A mistake usually makes me question whether I can do anything well.", True),
("self_confidence", "I can handle being evaluated without becoming overly self-conscious.", False),
("self_confidence", "I avoid expressing disagreement because I fear looking foolish.", True),
("self_confidence", "I am comfortable taking responsibility for a task within my ability.", False),
("leadership", "When a group has no clear plan, I am willing to suggest one.", False),
("leadership", "I can delegate a task according to people's strengths.", False),
("leadership", "I avoid giving constructive feedback because I dislike conflict.", True),
("leadership", "I can keep a group focused when discussion becomes scattered.", False),
("leadership", "I take the initiative to clarify roles when responsibilities overlap.", False),
("leadership", "I think being in charge means I should rarely listen to others.", True),
("leadership", "I can remain accountable for a group decision I supported.", False),
("leadership", "I try to keep weaker team members involved rather than ignoring them.", False),
("leadership", "I hesitate to act when a group needs someone to make a timely choice.", True),
("leadership", "I can encourage people without making unrealistic promises.", False),
("teamwork", "I try to make sure quieter teammates have a chance to contribute.", False),
("teamwork", "I share workload fairly instead of keeping easy tasks for myself.", False),
("teamwork", "I become defensive when a teammate points out a problem in my work.", True),
("teamwork", "I can cooperate even when I do not personally like a teammate.", False),
("teamwork", "I ask teammates for their input before making a group-related choice.", False),
("teamwork", "I see another person's mistake as a reason to stop trusting the whole team.", True),
("teamwork", "I support useful ideas even when I did not think of them myself.", False),
("teamwork", "I can adjust my contribution when the group is short of a particular skill.", False),
("teamwork", "I prefer recognition for myself over recognition for the entire team.", True),
("teamwork", "I can maintain cooperation after a disagreement is resolved.", False),
("emotional_stability", "I can remain practical when a stressful event cannot be changed immediately.", False),
("emotional_stability", "I usually recover my concentration after an unexpected problem.", False),
("emotional_stability", "I replay upsetting events in my mind for a long time.", True),
("emotional_stability", "I can delay an emotional response until I understand what happened.", False),
("emotional_stability", "I tend to panic when I cannot predict what will happen next.", True),
("emotional_stability", "Even under criticism, I can focus on what needs to be improved.", False),
("emotional_stability", "My frustration often makes me treat small problems as major ones.", True),
("emotional_stability", "I can continue functioning normally after receiving disappointing news.", False),
("emotional_stability", "When stressed, I find it hard to think of more than one possible solution.", True),
("emotional_stability", "I can stay patient while waiting for a situation to become clearer.", False),
("integrity", "I would correct an advantage I received by mistake rather than keep it.", False),
("integrity", "I keep confidential information private when I have agreed to do so.", False),
("integrity", "I can justify dishonesty when the other person will probably never know.", True),
("integrity", "I admit when my explanation for a mistake was incomplete.", False),
("integrity", "I try to be fair even when favoritism would benefit me.", False),
("integrity", "A useful result makes dishonest methods acceptable in my view.", True),
("integrity", "I follow through on ethical standards even when they are inconvenient.", False),
("integrity", "I would rather ask permission than assume I am entitled to something.", False),
("integrity", "I sometimes hide important facts to avoid an uncomfortable conversation.", True),
("integrity", "I respect other people's property even when there is little chance of being caught.", False),
("responsibility", "I keep track of important commitments without relying entirely on reminders.", False),
("responsibility", "I start major assignments early enough to leave room for problems.", False),
("responsibility", "When I miss a duty, my first reaction is usually to blame someone else.", True),
("responsibility", "I inform others early when I realize I may miss a deadline.", False),
("responsibility", "I double-check instructions before beginning an important task.", False),
("responsibility", "I sometimes agree to responsibilities without intending to complete them.", True),
("responsibility", "I try to fix a problem instead of waiting for someone else to notice it.", False),
("responsibility", "I take the impact of my choices on others seriously.", False),
("responsibility", "I often lose track of commitments when several tasks compete for attention.", True),
("responsibility", "I can be relied on to finish routine duties consistently.", False),
("adaptability", "I can change my method when new information makes the old method weaker.", False),
("adaptability", "I can become useful in a new team without needing everything to feel familiar first.", False),
("adaptability", "I resist new procedures even after I understand their advantages.", True),
("adaptability", "I can learn from people who use approaches different from mine.", False),
("adaptability", "I revise plans when circumstances change rather than insisting on the original route.", False),
("adaptability", "Unexpected instructions can make me unable to decide what to do next.", True),
("adaptability", "I can accept a temporary setback while adjusting my strategy.", False),
("adaptability", "I am curious about unfamiliar ways of solving a problem.", False),
("adaptability", "I dislike experimenting with a new approach even when the current one fails.", True),
("adaptability", "I can change priorities when a more important issue appears.", False),
("communication", "I check that my instructions were understood before assuming the task is clear.", False),
("communication", "I can explain disagreement without making the discussion personal.", False),
("communication", "I leave important details unsaid because I expect others to figure them out.", True),
("communication", "I can summarize a complicated issue into its main points.", False),
("communication", "I try to understand someone's concern before defending my own position.", False),
("communication", "I avoid asking questions because I do not want others to think I am uninformed.", True),
("communication", "I can speak honestly without deliberately embarrassing another person.", False),
("communication", "I adjust my explanation when the listener is clearly confused.", False),
("communication", "I sometimes respond before I have fully understood what was said.", True),
("communication", "I can receive criticism without responding with sarcasm or hostility.", False),
("initiative", "I look for useful work when my assigned task is finished.", False),
("initiative", "I am willing to test a practical idea instead of only discussing it.", False),
("initiative", "I usually wait until a problem becomes serious before taking action.", True),
("initiative", "I can identify a reasonable first step even when the full solution is uncertain.", False),
("initiative", "I volunteer to learn skills that may be useful later.", False),
("initiative", "I avoid taking ownership because someone else may criticize my decision.", True),
("initiative", "I prepare materials or information before they are urgently needed.", False),
("initiative", "I try to solve straightforward problems myself before seeking unnecessary help.", False),
("initiative", "I frequently need others to create momentum before I start a task.", True),
("initiative", "I act on constructive feedback rather than only agreeing with it.", False),
("discipline", "I can maintain good habits even when there is no immediate reward.", False),
("discipline", "I set aside regular time for important long-term goals.", False),
("discipline", "I regularly choose easy distractions over work that I know matters.", True),
("discipline", "I can finish a task before moving to something more entertaining.", False),
("discipline", "I keep commitments to routines that support my priorities.", False),
("discipline", "I often ignore schedules once something more interesting appears.", True),
("discipline", "I prepare what I need before beginning an important activity.", False),
("discipline", "I can return to a task after a distraction without abandoning it.", False),
("discipline", "I depend on last-minute urgency because I rarely start early.", True),
("discipline", "I follow safety or quality rules even when supervision is limited.", False),
]

EXTRA_PAIR = [
("self_confidence", "I can express a reasonable opinion without first checking whether everyone agrees.", False),
("self_confidence", "I can approach a new responsibility with realistic confidence.", False),
("self_confidence", "I often assume people will notice my shortcomings more than my strengths.", True),
("self_confidence", "I can accept that I am still learning without feeling inferior.", False),
("self_confidence", "Being around highly skilled people often makes me hold back.", True),
("self_confidence", "I can explain why I chose one option over another.", False),
("self_confidence", "After a poor result, I quickly doubt my overall ability.", True),
("self_confidence", "Evaluation makes me nervous, but I can still perform normally.", False),
("self_confidence", "I stay silent rather than risk an unpopular opinion.", True),
("self_confidence", "I am prepared to take ownership of work I know I can handle.", False),
("leadership", "I am willing to propose a workable plan when others are unsure.", False),
("leadership", "I distribute responsibilities according to what each person can contribute.", False),
("leadership", "I avoid useful criticism because I want everyone to like me.", True),
("leadership", "I redirect a discussion when a team loses sight of its objective.", False),
("leadership", "I help clarify who should handle overlapping responsibilities.", False),
("leadership", "Once I am the leader, other people's opinions are usually unnecessary.", True),
("leadership", "I remain answerable for decisions that I helped lead.", False),
("leadership", "I try to involve less confident members instead of speaking for everyone.", False),
("leadership", "I postpone difficult choices even when delay will clearly hurt the group.", True),
("leadership", "I motivate people with realistic encouragement rather than empty promises.", False),
("teamwork", "I make space for teammates who speak less often.", False),
("teamwork", "I contribute my fair share instead of protecting myself from difficult work.", False),
("teamwork", "Useful criticism from a teammate often makes me defensive.", True),
("teamwork", "I can work respectfully with someone whose personality I dislike.", False),
("teamwork", "I consult teammates when a decision will affect their work.", False),
("teamwork", "One teammate's mistake can make me lose trust in everyone.", True),
("teamwork", "I support strong ideas even when they come from someone else.", False),
("teamwork", "I can change my role when the team's needs change.", False),
("teamwork", "I care more about personal credit than collective success.", True),
("teamwork", "I can continue cooperating after a disagreement has ended.", False),
("emotional_stability", "I can focus on practical action even when a stressful event is unresolved.", False),
("emotional_stability", "After an unexpected problem, I can usually regain concentration.", False),
("emotional_stability", "I continue thinking about minor upsetting events long after they happen.", True),
("emotional_stability", "I can hold back an emotional reaction until I understand the situation.", False),
("emotional_stability", "Uncertainty often makes me panic before I know the facts.", True),
("emotional_stability", "Criticism can upset me without stopping me from improving.", False),
("emotional_stability", "Frustration sometimes makes ordinary problems feel much bigger than they are.", True),
("emotional_stability", "Disappointing news does not necessarily prevent me from functioning normally.", False),
("emotional_stability", "Under stress, I can usually consider more than one possible solution.", False),
("emotional_stability", "I can wait calmly when an outcome is outside my control.", False),
("integrity", "I correct an accidental advantage instead of treating it as mine.", False),
("integrity", "I protect private information that someone trusted me with.", False),
("integrity", "Dishonesty seems acceptable to me when there is almost no chance of discovery.", True),
("integrity", "I admit when part of my explanation for a mistake was wrong.", False),
("integrity", "I avoid favoritism when making a fair decision.", False),
("integrity", "A good outcome can justify dishonest behavior in my view.", True),
("integrity", "I keep ethical standards even when doing so is inconvenient.", False),
("integrity", "I ask before using something that is not clearly mine to use.", False),
("integrity", "I sometimes leave out important facts to avoid discomfort.", True),
("integrity", "I respect other people's belongings even without supervision.", False),
("responsibility", "I monitor important obligations without needing repeated reminders.", False),
("responsibility", "I begin major work early enough to manage unexpected difficulties.", False),
("responsibility", "When I fail a duty, I quickly look for someone else to blame.", True),
("responsibility", "I warn people in advance when a deadline may be missed.", False),
("responsibility", "I verify key instructions before carrying out an important task.", False),
("responsibility", "I sometimes accept duties even though I do not plan to finish them.", True),
("responsibility", "I try to address problems before someone else has to point them out.", False),
("responsibility", "I consider how my decisions may affect other people.", False),
("responsibility", "Multiple commitments can easily cause me to forget important duties.", True),
("responsibility", "People can normally trust me to complete routine responsibilities.", False),
("adaptability", "I change my method when new information shows a better path.", False),
("adaptability", "I can contribute to a new group without waiting to feel completely comfortable.", False),
("adaptability", "I resist new procedures even after I see their value.", True),
("adaptability", "I can learn useful techniques from someone with a different style.", False),
("adaptability", "I modify my plan when circumstances make the original approach unsuitable.", False),
("adaptability", "Unexpected instructions can leave me unable to decide how to proceed.", True),
("adaptability", "I can accept temporary failure and adjust my strategy.", False),
("adaptability", "I am interested in unfamiliar methods when they might work better.", False),
("adaptability", "I keep using an ineffective method because trying something new feels uncomfortable.", True),
("adaptability", "I can change priorities when circumstances make another issue more urgent.", False),
("communication", "I confirm that an important instruction has been understood.", False),
("communication", "I can explain my disagreement without attacking the person.", False),
("communication", "I leave key information unstated because I expect others to infer it.", True),
("communication", "I can reduce a complicated topic to the main points.", False),
("communication", "I listen to the concern behind a person's words before defending myself.", False),
("communication", "I avoid questions because I worry they will make me look uninformed.", True),
("communication", "I can be honest without humiliating the other person.", False),
("communication", "I change my explanation when I can see that it is not being understood.", False),
("communication", "I sometimes answer before I fully understand what was said.", True),
("communication", "I can hear criticism without becoming sarcastic or hostile.", False),
("initiative", "When assigned work is complete, I look for another useful contribution.", False),
("initiative", "I am willing to try a practical idea rather than discussing it forever.", False),
("initiative", "I often wait until a problem becomes severe before doing anything.", True),
("initiative", "I can choose a sensible first action even when the final answer is unclear.", False),
("initiative", "I volunteer to learn skills that may become useful later.", False),
("initiative", "Fear of criticism often stops me from taking ownership.", True),
("initiative", "I prepare information before it becomes urgently necessary.", False),
("initiative", "For straightforward problems, I usually try an initial solution myself.", False),
("initiative", "I often need someone else to get things started before I contribute.", True),
("initiative", "I turn useful feedback into a concrete action.", False),
("discipline", "I can maintain important habits even without an immediate reward.", False),
("discipline", "I reserve regular time for goals that matter over the long term.", False),
("discipline", "I often choose entertainment over work that I know is important.", True),
("discipline", "I can complete a necessary task before doing something more enjoyable.", False),
("discipline", "I keep routines that support my most important priorities.", False),
("discipline", "Interesting distractions often cause me to abandon my schedule.", True),
("discipline", "I prepare essential materials before starting an important activity.", False),
("discipline", "After a distraction, I can return to the original task.", False),
("discipline", "I regularly rely on last-minute pressure because I delay starting.", True),
("discipline", "I follow important safety or quality procedures even with little supervision.", False),
]

assert len(EXTRA_BASE) == 100 and len(EXTRA_PAIR) == 100

# Rebuild the bank cleanly: 200 original items + 200 additional items = 400 total.
ALL_PAIRS = []
for idx, (trait, stem, reverse) in enumerate(BASE, start=1):
    # BASE is a flat list; group each 10 statements as the first member of pairs.
    pass

# Existing 100 pair relationship is already encoded in PAIR_BASE; recreate those 100 pairs.
QUESTIONS = []
qid = 1
pair_no = 1
for idx, (trait, stem, reverse) in enumerate(BASE, start=1):
    QUESTIONS.append({"id": f"Q{qid:03d}", "trait": trait, "text": stem, "reverse": reverse,
                      "pair_id": f"P{idx:03d}", "paired_question_id": f"Q{qid+100:03d}"})
    qid += 1
# Pair_BASE order corresponds exactly to BASE order: item 1 pairs with item 101, ..., item 100 with item 200.
for idx, (trait, stem, reverse) in enumerate(PAIR_BASE, start=1):
    QUESTIONS.append({"id": f"Q{qid:03d}", "trait": trait, "text": stem, "reverse": reverse,
                      "pair_id": f"P{idx:03d}", "paired_question_id": f"Q{idx:03d}"})
    qid += 1

# Additional 100 pairs become P101-P200, with questions Q201-Q300 and Q301-Q400.
for idx, ((trait, stem, reverse), (trait2, stem2, reverse2)) in enumerate(zip(EXTRA_BASE, EXTRA_PAIR), start=101):
    assert trait == trait2
    first_id = qid
    second_id = qid + 100
    QUESTIONS.append({"id": f"Q{first_id:03d}", "trait": trait, "text": stem, "reverse": reverse,
                      "pair_id": f"P{idx:03d}", "paired_question_id": f"Q{second_id:03d}"})
    qid += 1
# Extra second forms are stored after all first forms.
for idx, (trait, stem, reverse) in enumerate(EXTRA_PAIR, start=101):
    first_id = idx + 100
    # First member Q201 corresponds idx 101; second member is Q301.
    QUESTIONS.append({"id": f"Q{qid:03d}", "trait": trait, "text": stem, "reverse": reverse,
                      "pair_id": f"P{idx:03d}", "paired_question_id": f"Q{idx+100:03d}"})
    qid += 1

assert len(QUESTIONS) == 400, len(QUESTIONS)
